# Spring Boot configuration
spring:
  # Database
  datasource:
    database-type: MySQL
    database-name: # db_name
    database-ip: # 0.0.0.0:0000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.database-ip}/${spring.datasource.database-name}
    username: # username
    password: # password
  # JPA properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update # none, validate, update, create, create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
